---
- hosts: flik
  become: yes
  become_method: sudo

  tasks:
  - name: disable SElinux
    selinux:
      state: disabled
  - name : Install the 'ntp package.
    yum:
      name: ntp
      state: present