---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: disable SElinux
    selinux:
      state: disabled
  - name : Install the 'ntp package.
    yum:
      name: ntp
      state: present

- hosts: atta
  vars: 
    ntp_servers: ['0.de.pool.ntp.org', '1.de.pool.ntp.org', '2.de.pool.ntp.org']
  become: yes
  become_method: sudo
  tasks:
  - name: Set up NTP server config file
    template:
      src: templates/ntp.conf.j2
      dest: /etc/ntp.conf
  - service:
      name: ntpd
      enabled: yes
      state: started

    
